import { Song } from '../interfaces/songs.interface';

export const musicMockData: Song[] = [
  {
    id: 1,
    title: 'Summer Breeze',
    artist: 'Amanda Smith',
    album: 'Sunny Days',
    songWriter: 'Amanda Smith',
    genre: 'Pop',
    year: 2019,
    rating: 4.5,
  },
  {
    id: 2,
    title: 'Midnight Serenade',
    artist: 'John Johnson',
    album: 'Moonlight Melodies',
    songWriter: 'John Johnson',
    genre: 'Jazz',
    year: 2020,
    rating: 4.2,
  },
  {
    id: 3,
    title: 'Ocean Dreams',
    artist: 'Sara Anderson',
    album: 'Waves of Peace',
    songWriter: 'Sara Anderson',
    genre: 'Ambient',
    year: 2018,
    rating: 4.8,
  },
  {
    id: 4,
    title: 'Lost in the City',
    artist: 'The Urbanites',
    album: 'Metropolis',
    songWriter: 'Mike Davis',
    genre: 'Rock',
    year: 2017,
    rating: 4.0,
  },
  {
    id: 5,
    title: 'Eternal Love',
    artist: 'Sophie Turner',
    album: 'Timeless',
    songWriter: 'Sophie Turner',
    genre: 'Pop',
    year: 2022,
    rating: 4.7,
  },
  {
    id: 6,
    title: 'Guitar Groove',
    artist: 'Carlos Rodriguez',
    album: 'Strings Unleashed',
    songWriter: 'Carlos Rodriguez',
    genre: 'Latin',
    year: 2016,
    rating: 4.3,
  },
  {
    id: 7,
    title: 'Rhythm of the Rain',
    artist: 'The Raindrops',
    album: 'Liquid Harmony',
    songWriter: 'Linda Williams',
    genre: 'Pop',
    year: 2015,
    rating: 4.6,
  },
  {
    id: 8,
    title: 'Sunset Serenade',
    artist: 'Ella Davis',
    album: 'Evening Echoes',
    songWriter: 'Ella Davis',
    genre: 'Jazz',
    year: 2019,
    rating: 4.4,
  },
  {
    id: 9,
    title: 'Whispers in the Wind',
    artist: 'David White',
    album: 'Mystic Moments',
    songWriter: 'David White',
    genre: 'Ambient',
    year: 2021,
    rating: 4.9,
  },
  {
    id: 10,
    title: 'City Lights',
    artist: 'The Urbanites',
    album: 'Urban Vibes',
    songWriter: 'Mike Davis',
    genre: 'Electronic',
    year: 2018,
    rating: 4.1,
  },
  {
    id: 11,
    title: 'Sail Away',
    artist: 'Emily Turner',
    album: 'Horizon',
    songWriter: 'Emily Turner',
    genre: 'Pop',
    year: 2020,
    rating: 4.7,
  },
  {
    id: 12,
    title: 'Salsa Fiesta',
    artist: 'Juan Martinez',
    album: 'Latin Nights',
    songWriter: 'Juan Martinez',
    genre: 'Latin',
    year: 2017,
    rating: 4.2,
  },
  {
    id: 13,
    title: 'Moonlit Memories',
    artist: 'Sarah Johnson',
    album: 'Nocturnal Nostalgia',
    songWriter: 'Sarah Johnson',
    genre: 'Jazz',
    year: 2019,
    rating: 4.5,
  },
  {
    id: 14,
    title: 'Tranquil Waters',
    artist: 'Daniel Smith',
    album: 'Serene Seas',
    songWriter: 'Daniel Smith',
    genre: 'Ambient',
    year: 2021,
    rating: 4.8,
  },
  {
    id: 15,
    title: 'Urban Groove',
    artist: 'The Urbanites',
    album: 'Metropolis Remix',
    songWriter: 'Mike Davis',
    genre: 'Electronic',
    year: 2020,
    rating: 4.0,
  },
  {
    id: 16,
    title: 'Infinite Love',
    artist: 'Sophia Johnson',
    album: 'Endless Emotions',
    songWriter: 'Sophia Johnson',
    genre: 'Pop',
    year: 2023,
    rating: 4.6,
  },
  {
    id: 17,
    title: 'Samba Rhythms',
    artist: 'Antonio Silva',
    album: 'Samba Party',
    songWriter: 'Antonio Silva',
    genre: 'Latin',
    year: 2017,
    rating: 4.3,
  },
  {
    id: 18,
    title: 'Rainy Reflections',
    artist: 'Lucas Miller',
    album: 'Wet Echoes',
    songWriter: 'Lucas Miller',
    genre: 'Ambient',
    year: 2019,
    rating: 4.9,
  },
  {
    id: 19,
    title: 'Cityscape Dreams',
    artist: 'The Urbanites',
    album: 'Cityscape',
    songWriter: 'Mike Davis',
    genre: 'Electronic',
    year: 2016,
    rating: 4.2,
  },
  {
    id: 20,
    title: 'Golden Sunset',
    artist: 'Olivia Turner',
    album: 'Golden Hour',
    songWriter: 'Olivia Turner',
    genre: 'Pop',
    year: 2022,
    rating: 4.7,
  },
];
